version: "3.8"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    networks:
      - media_net
      - traefik_proxy
      - default
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.entrypoints=https
      - traefik.http.routers.overseerr.rule=Host(`overseerr.media.hyeon.pro`)
      - traefik.http.routers.overseerr.tls.certresolver=leresolver
      - traefik.http.services.overseerr.loadbalancer.server.port=5055

########################### NETWORKS
networks:
  media_net:
    external: true
  traefik_proxy:
    external: true
