version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    networks:
      - media_net
      - traefik_proxy
      - default
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
    volumes:
      - ./.docker/config:/config
      - ../media/영화:/movies #optional
      - ../media/INBOX:/downloads #optional
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=https
      - traefik.http.routers.radarr.rule=Host(`radarr.media.hyeon.pro`)
      - traefik.http.routers.radarr.tls.certresolver=leresolver
      - traefik.http.services.radarr.loadbalancer.server.port=7878

########################### NETWORKS
networks:
  media_net:
    external: true
  traefik_proxy:
    external: true
